### ISSUE TITLE
Meteor error

### ISSUE THREAD

**Issue by legacyWork** [eduardogch/gulp-chimp#1]
[09:50:30] Starting 'chimp-options'...
[09:50:30] 'chimp-options' errored after 554 μs
[09:50:30] TypeError: this._handleMeteorInterrupt is not a function

**Comment by eduardogch** [comment]
aghhhhh let's see what's happen here!

**Comment by eduardogch** [comment]
Fix now, please check version 1.0.8

**Comment by legacyWork** [comment]
hmm. I am still getting the error

package.json dependencies:

 "devDependencies": {
    "babel-eslint": "^6.0.3",
    "chimp": "^0.25.1",
    "eslint": "^2.8.0",
    "eslint-plugin-react": "^5.0.1",
    "gulp-chimp": "^1.0.8",
    "karma-mocha-reporter": "^1.2.3",
    "selenium-standalone": "^5.1.1",
    "xunit-file": "0.0.9"
  },

chimp-config.js:

'use strict';

var _path = require('path');

var _path2 = _interopRequireDefault(_path);

// var _ci = require('../lib/ci');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

module.exports = {
    // - - - - CHIMP - - - -
    watch: false,
    // @focus is recommended to use. @dev and @watch are deprecated.
    watchTags: '@focus,@dev,@watch',
    watchWithPolling: false,
    criticalSteps: null,
    criticalTag: '@critical',
    server: false,
    serverPort: 8060,
    serverHost: 'localhost',
    sync: true,
    offline: false,

```
// - - - - CUCUMBER - - - -
path: './features',
format: 'pretty',
tags: '~@ignore',
singleSnippetPerFile: true,
recommendedFilenameSeparator: '_',
chai: true,
// screenshotsOnError: (0, _ci.isCI)(),
screenshotsPath: '.screenshots',
captureAllStepScreenshots: false,
saveScreenshotsToDisk: true,
// Note: With a large viewport size and captureAllStepScreenshots enabled,
// you may run out of memory. Use browser.setViewportSize to make the
// viewport size smaller.
saveScreenshotsToReport: false,
jsonOutput: null,
compiler: 'js:' + _path2.default.resolve(__dirname, '../lib/babel-register.js'),

// - - - - SELENIUM  - - - -
browser: 'chrome',
platform: 'ANY',
name: '',
user: '',
key: '',
port: 4443,
host: null,
// deviceName: null,

// - - - - WEBDRIVER-IO  - - - -
webdriverio: {
    desiredCapabilities: {},
    logLevel: 'silent',
    // logOutput: null,
    host: '127.0.0.1',
    port: 4444,
    path: '/wd/hub',
    baseUrl: null,
    coloredLogs: true,
    screenshotPath: null,
    waitforTimeout: 500,
    waitforInterval: 250
},

// - - - - SESSION-MANAGER  - - - -
noSessionReuse: false,

// - - - - SIMIAN  - - - -
simianResultEndPoint: 'api.simian.io/v1.0/result',
simianAccessToken: false,
simianResultBranch: null,
simianRepositoryId: null,

// - - - - MOCHA  - - - -
mocha: true,
// 'path: './tests',
mochaTimeout: 60000,
mochaReporter: 'spec',
mochaSlow: 10000,

// - - - - JASMINE  - - - -
jasmine: false,
jasmineConfig: {
    specDir: '.',
    specFiles: ['**/*@(_spec|-spec|Spec).@(js|jsx)'],
    helpers: ['support/**/*.@(js|jsx)'],
    stopSpecOnExpectationFailure: false,
    random: false
},
jasmineReporterConfig: {
    // This options are passed to jasmine.configureDefaultReporter(...)
    // See: http://jasmine.github.io/2.4/node.html#section-Reporters
},

// - - - - METEOR  - - - -
ddp: false,

// - - - - PHANTOM  - - - -
phantom_w: 1280,
phantom_h: 1024,

// - - - - DEBUGGING  - - - -
log: 'info',
debug: false,
seleniumDebug: null,
debugCucumber: null,
debugBrkCucumber: null,
debugMocha: null,
debugBrkMocha: null
```

};

gulpfile.js:

var gulp = require('gulp')
var selenium = require('selenium-standalone')
var chimp = require('chimp')

gulp.task('chimp', function () {
    return chimp('./.config/chimp-config.js');
});

gulp output complete:

[14:15:57] Using gulpfile ~/AUTOMATION/AutomationDev/javascript_ui_test/gulpfile.js
[14:15:57] Starting 'chimp'...
[14:15:57] 'chimp' errored after 2.96 ms
[14:15:57] TypeError: this._handleMeteorInterrupt is not a function
    at Chimp (/Users/me/AUTOMATION/AutomationDev/javascript_ui_test/node_modules/chimp/lib/chimp.js:65:8)
    at Gulp.<anonymous> 
(/Users/me/AUTOMATION/AutomationDev/javascript_ui_test/gulpfile.js:6:12)
    at module.exports (/Users/me/AUTOMATION/AutomationDev/javascript_ui_test/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/me/AUTOMATION/AutomationDev/javascript_ui_test/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/me/AUTOMATION/AutomationDev/javascript_ui_test/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/me/AUTOMATION/AutomationDev/javascript_ui_test/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
    at node.js:404:3
➜  javascript_ui_test git:(master) ✗

**Comment by eduardogch** [comment]
Try this chimp config [chimp.conf.js](https://github.com/eduardogch/gulp-chimp/blob/master/chimp.conf.js)

in package.json just need gulp-chimp

```
var chimp = require('chimp');

gulp.task('chimp', function () {
return chimp('./chimp-config.js');
});
```

**Comment by legacyWork** [comment]
I was able to get the test to start but none of the test run and it finishes with 0 passed 0 failing. No browser opens.

**Comment by legacyWork** [comment]
I am still getting the meteor error

**Comment by eduardogch** [comment]
Try Version 1.0.9
