### ISSUE TITLE
Problems installing this package...

### ISSUE THREAD

**Issue by mario-ortiz** [eduardogch/gulp-chimp#4]
Hello,

I'm having problems installing this package:

C:\Users\sg0951798\workspace\automation>npm install gulp-chimp --save-dev
npm ERR! tar.unpack untar error C:\Users\sg0951798\AppData\Roaming\npm-cache\gulp-chimp\1.1.0\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "gulp-chimp" "--save-dev"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path C:\Users\sg0951798\workspace\automation\node_modules\gulp-chimp\source\output\screenshots\Shouldtitlebe"HolaGulpChimp.js"@focus.png
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\sg0951798\workspace\automation\node_modules\gulp-chimp\source\output\screenshots\Shouldtitlebe"HolaGulpChimp.js"@focus.png'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sg0951798\workspace\automation\npm-debug.log

Hope you can help me with this.

**Comment by eduardogch** [comment]
Hello, sure I'm working to update gulp-chimp to the new version 0.4.11 and hope that will fix the npm dependencies

**Comment by eduardogch** [comment]
Fix in the new version 1.5.5
